import { Topic } from "./types";

export const topics: Topic[] = [
  {
    id: "1",
    title: "Was dropping the atomic bomb justified?",
    description:
      "The decision to use nuclear weapons on Hiroshima and Nagasaki remains one of history's most debated moral questions. Did it save more lives by ending the war, or was it an unforgivable act of mass destruction?",
    category: "History",
    status: "voting",
    votingEndsAt: new Date(Date.now() + 3 * 3600000).toISOString(),
    debateAt: null,
    forSide: {
      label: "Justified",
      debaters: [
        {
          id: "f1",
          name: "J. Robert Oppenheimer",
          title: "Father of the Atomic Bomb",
          avatar: "JO",
          votes: 4823,
        },
        {
          id: "f2",
          name: "Harry S. Truman",
          title: "33rd U.S. President",
          avatar: "HT",
          votes: 3291,
        },
        {
          id: "f3",
          name: "Winston Churchill",
          title: "British Prime Minister",
          avatar: "WC",
          votes: 2847,
        },
        {
          id: "f4",
          name: "Henry Stimson",
          title: "U.S. Secretary of War",
          avatar: "HS",
          votes: 1456,
        },
        {
          id: "f5",
          name: "Paul Tibbets",
          title: "Enola Gay Pilot",
          avatar: "PT",
          votes: 982,
        },
      ],
    },
    againstSide: {
      label: "Unjustified",
      debaters: [
        {
          id: "a1",
          name: "Albert Einstein",
          title: "Theoretical Physicist",
          avatar: "AE",
          votes: 5102,
        },
        {
          id: "a2",
          name: "Mahatma Gandhi",
          title: "Leader of Indian Independence",
          avatar: "MG",
          votes: 4567,
        },
        {
          id: "a3",
          name: "Leo Szilard",
          title: "Nuclear Physicist & Petitioner",
          avatar: "LS",
          votes: 2103,
        },
        {
          id: "a4",
          name: "Dwight D. Eisenhower",
          title: "Supreme Allied Commander",
          avatar: "DE",
          votes: 1890,
        },
        {
          id: "a5",
          name: "Sadako Sasaki",
          title: "Hiroshima Survivor Symbol",
          avatar: "SS",
          votes: 3421,
        },
      ],
    },
    totalVotes: 30482,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "2",
    title: "Is AI an existential threat to humanity?",
    description:
      "As artificial intelligence grows more capable, the debate intensifies: will AI be humanity's greatest tool, or its final invention?",
    category: "Technology",
    status: "voting",
    votingEndsAt: new Date(Date.now() + 8 * 3600000).toISOString(),
    debateAt: null,
    forSide: {
      label: "Yes, Existential Threat",
      debaters: [
        {
          id: "f6",
          name: "Elon Musk",
          title: "CEO of Tesla & SpaceX",
          avatar: "EM",
          votes: 7823,
        },
        {
          id: "f7",
          name: "Nick Bostrom",
          title: "Author of Superintelligence",
          avatar: "NB",
          votes: 3102,
        },
        {
          id: "f8",
          name: "Eliezer Yudkowsky",
          title: "AI Safety Researcher",
          avatar: "EY",
          votes: 2945,
        },
        {
          id: "f9",
          name: "Stephen Hawking",
          title: "Theoretical Physicist",
          avatar: "SH",
          votes: 5671,
        },
        {
          id: "f10",
          name: "Stuart Russell",
          title: "AI Professor, UC Berkeley",
          avatar: "SR",
          votes: 1234,
        },
      ],
    },
    againstSide: {
      label: "No, Greatest Tool",
      debaters: [
        {
          id: "a6",
          name: "Andrew Ng",
          title: "AI Pioneer & Educator",
          avatar: "AN",
          votes: 4521,
        },
        {
          id: "a7",
          name: "Yann LeCun",
          title: "Chief AI Scientist, Meta",
          avatar: "YL",
          votes: 3890,
        },
        {
          id: "a8",
          name: "Demis Hassabis",
          title: "CEO of DeepMind",
          avatar: "DH",
          votes: 5234,
        },
        {
          id: "a9",
          name: "Fei-Fei Li",
          title: "Stanford AI Lab Director",
          avatar: "FL",
          votes: 2876,
        },
        {
          id: "a10",
          name: "Ray Kurzweil",
          title: "Futurist & Inventor",
          avatar: "RK",
          votes: 4102,
        },
      ],
    },
    totalVotes: 45398,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "3",
    title: "Should colonizing Mars be humanity's priority?",
    description:
      "With climate change accelerating and Earth's resources depleting, should we invest trillions in becoming a multi-planetary species, or focus on fixing our home planet first?",
    category: "Science",
    status: "scheduled",
    votingEndsAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    debateAt: new Date(Date.now() + 5 * 3600000).toISOString(),
    forSide: {
      label: "Yes, Go to Mars",
      debaters: [
        {
          id: "f11",
          name: "Elon Musk",
          title: "SpaceX Founder",
          avatar: "EM",
          votes: 12340,
        },
        {
          id: "f12",
          name: "Robert Zubrin",
          title: "Mars Society President",
          avatar: "RZ",
          votes: 4521,
        },
        {
          id: "f13",
          name: "Buzz Aldrin",
          title: "Apollo 11 Astronaut",
          avatar: "BA",
          votes: 8912,
        },
        {
          id: "f14",
          name: "Carl Sagan",
          title: "Astronomer & Author",
          avatar: "CS",
          votes: 11203,
        },
        {
          id: "f15",
          name: "Gwynne Shotwell",
          title: "SpaceX President",
          avatar: "GS",
          votes: 3456,
        },
      ],
    },
    againstSide: {
      label: "No, Fix Earth First",
      debaters: [
        {
          id: "a11",
          name: "Greta Thunberg",
          title: "Climate Activist",
          avatar: "GT",
          votes: 9823,
        },
        {
          id: "a12",
          name: "Neil deGrasse Tyson",
          title: "Astrophysicist",
          avatar: "NT",
          votes: 7654,
        },
        {
          id: "a13",
          name: "Bill Gates",
          title: "Philanthropist & Technologist",
          avatar: "BG",
          votes: 6789,
        },
        {
          id: "a14",
          name: "David Attenborough",
          title: "Naturalist & Broadcaster",
          avatar: "DA",
          votes: 10234,
        },
        {
          id: "a15",
          name: "Jane Goodall",
          title: "Primatologist & Activist",
          avatar: "JG",
          votes: 5432,
        },
      ],
    },
    totalVotes: 80364,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: "4",
    title: "Is social media destroying democracy?",
    description:
      "From misinformation to echo chambers, social media platforms have transformed political discourse. Are they empowering citizens or eroding democratic institutions?",
    category: "Politics",
    status: "voting",
    votingEndsAt: new Date(Date.now() + 12 * 3600000).toISOString(),
    debateAt: null,
    forSide: {
      label: "Yes, Destroying It",
      debaters: [
        {
          id: "f16",
          name: "Tristan Harris",
          title: "Center for Humane Tech",
          avatar: "TH",
          votes: 6234,
        },
        {
          id: "f17",
          name: "Shoshana Zuboff",
          title: "Surveillance Capitalism Author",
          avatar: "SZ",
          votes: 3456,
        },
        {
          id: "f18",
          name: "Frances Haugen",
          title: "Facebook Whistleblower",
          avatar: "FH",
          votes: 5678,
        },
        {
          id: "f19",
          name: "Noam Chomsky",
          title: "Linguist & Political Critic",
          avatar: "NC",
          votes: 7890,
        },
        {
          id: "f20",
          name: "Jaron Lanier",
          title: "Tech Philosopher",
          avatar: "JL",
          votes: 4567,
        },
      ],
    },
    againstSide: {
      label: "No, Empowering Citizens",
      debaters: [
        {
          id: "a16",
          name: "Mark Zuckerberg",
          title: "CEO of Meta",
          avatar: "MZ",
          votes: 2345,
        },
        {
          id: "a17",
          name: "Jack Dorsey",
          title: "Twitter Co-founder",
          avatar: "JD",
          votes: 3210,
        },
        {
          id: "a18",
          name: "Malala Yousafzai",
          title: "Education Activist",
          avatar: "MY",
          votes: 8901,
        },
        {
          id: "a19",
          name: "Wael Ghonim",
          title: "Egyptian Revolution Activist",
          avatar: "WG",
          votes: 5432,
        },
        {
          id: "a20",
          name: "Clay Shirky",
          title: "Internet Culture Theorist",
          avatar: "CSh",
          votes: 2109,
        },
      ],
    },
    totalVotes: 50322,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];
